### ISSUE TITLE
Can we get it documented that this doesn't work with python 3.somthing+?

### ISSUE THREAD

**Issue by togakangaroo** [timClicks/slate#47]
On python 3.7

```
>>> import slate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gmauer/.local/share/virtualenvs/resume-parser-uEcoETqN/lib/python3.7/site-packages/slate/__init__.py", line 48, in <module>
    from slate import PDF
ImportError: cannot import name 'PDF' from 'slate' (/Users/gmauer/.local/share/virtualenvs/resume-parser-uEcoETqN/lib/python3.7/site-packages/slate/__init__.py)

```

Looking through the issues and unmerged PRs it seems like this doesn't work with some versions of python (3.4+ maybe?). I get that maintainers have limited amounts of time and so on, I am an OSS maintainer as well. But I've now 3 different pdf parsing libraries deep which I set up and start working with to find an issue like this. It is incredibly frustrating.

Can we at least document it toward the top of the readme which notes that the main pip version doesn't work with more recent python versions?
